[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neoedgex-python-template"
version = "2.1.0"
requires-python = ">=3.11"
dependencies = [
  "neoedgex-v4-app-sdk-python>=2.0.0,<3",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0.0,<10",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
